version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: flexgym_db
      POSTGRES_USER: flexgym_user
      POSTGRES_PASSWORD: your_secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flexgym_user -d flexgym_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://flexgym_user:your_secure_password_here@postgres:5432/flexgym_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src:ro

volumes:
  postgres_data: